[package]
name = "hello-dioxus"
version = "0.1.0"
authors = ["nissy-dev <nd.12021218@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.3.1" }
dioxus-web = { version = "0.3.0" }
dioxus-free-icons = { path = "../lib", features = ["font-awesome-brands"] }

log = "0.4.6"

# WebAssembly Debug
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"

[profile.release]
lto = true
opt-level = 's'
