[package]
name = "dioxus-fontawesome-examples"
version = "0.2.0"
edition = "2021"

[features]
default = ["render"]
render = ["dep:resvg", "dep:base64"]

[dependencies]
codegen = "0.1.3"
heck = "0.4.0"
regex = "1.6.0"
scraper = "0.13.0"
walkdir = "2.3.2"

resvg = { version = "0.41.0", optional = true }
base64 = { version = "0.22.0", optional = true }
